[package]
name = "eg_triton"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
triton-vm = { path = "deps/triton-vm/triton-vm" }
twenty-first = { version = "0.8.0" }
bincode = "1.3.3"
